[package]
name = "synopsys-usb-otg"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
description = "'usb-device' implementation for Synopsys USB OTG IP cores"
edition = "2018"
license = "MIT"
repository = "https://github.com/stm32-rs/synopsys-usb-otg"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]

[dependencies]
riscv = { version = "0.5.4", optional = true }
cortex-m = { version = "0.6.0", optional = true }
vcell = "0.1.0"
usb-device = "0.2.2"
stm32ral = { version = "0.3.1", features = ["stm32f429"] }

[dependencies.usb-device-ep]
package = "usb-device"
git = "https://github.com/mvirkkunen/usb-device.git"
rev = "327c7d08c8483c7e36306b5b9672083f5ca9317f"

[package.metadata.docs.rs]
features = ['cortex-m', 'fs']

[features]
hs = []
fs = []
stm32f429xx = ['cortex-m']
stm32f401xx = ['cortex-m', 'fs']
gd32vf103xx = ['riscv', 'fs']
