[package]
name = "synopsys-usb-otg"
version = "0.0.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
description = "'usb-device' implementation for Synopsys USB OTG IP cores"
edition = "2018"
license = "MIT"
repository = "https://github.com/stm32-rs/synopsys-usb-otg"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]

[dependencies]
riscv = { version = "0.5.4", optional = true }
cortex-m = { version = "0.6.0", optional = true }
vcell = "0.1.0"
usb-device = "0.2.2"

[dependencies.stm32ral]
git = "https://github.com/Disasm/stm32ral"
rev = "aa95c633b7bf535c96d7eac997deb361aabae87c"
features = ["stm32f429"]

[features]
hs = []
fs = []
stm32f429xx = ['cortex-m']
stm32f401xx = ['cortex-m', 'fs']
gd32vf103xx = ['riscv', 'fs']
