[package]
name = "stm32f429-usbd-fs"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.0"
vcell = "0.1.0"
stm32f4xx-hal = { version = "0.5.0", features = ["stm32f429"] }
usb-device = "0.2.1"
stm32ral = { version = "0.2.0", features = ["stm32f429"] }
